# Generated by Django 2.2.6 on 2019-10-19 01:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Corps',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'corps',
            },
        ),
        migrations.CreateModel(
            name='DocumentCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'document_categories',
            },
        ),
        migrations.CreateModel(
            name='Ministry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
            ],
            options={
                'verbose_name_plural': 'ministers',
            },
        ),
        migrations.CreateModel(
            name='PayingOrg',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'paying_orgs',
            },
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
        migrations.AddField(
            model_name='user',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, verbose_name='Lieu de naissance'),
        ),
        migrations.AddField(
            model_name='user',
            name='cni',
            field=models.CharField(blank=True, max_length=100, verbose_name="Numéro Carte d'identité"),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_date',
            field=models.DateField(blank=True, null=True, verbose_name="Date d'entrée"),
        ),
        migrations.AddField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Matricule'),
        ),
        migrations.AddField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Féminin'), (1, 'Masculin')], default=1, verbose_name='Sexe'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Nom'),
        ),
        migrations.CreateModel(
            name='Salary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.IntegerField(choices=[(0, 'Brute'), (1, 'NET')], verbose_name='Type')),
                ('amount', models.FloatField(verbose_name='Montant')),
                ('change_at', models.DateField(blank=True, null=True, verbose_name='Date mise à jour')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'salaries',
            },
        ),
        migrations.CreateModel(
            name='RequestCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='Nom')),
                ('description', models.TextField(verbose_name='Description')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('documents', models.ManyToManyField(to='users.DocumentCategory')),
            ],
            options={
                'verbose_name_plural': 'request_categories',
            },
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.FloatField(verbose_name='Montant de la demande')),
                ('date', models.DateField(verbose_name='Date de dépôt de la demande')),
                ('post_reference', models.CharField(max_length=20, verbose_name='Référence courier')),
                ('observations', models.TextField(blank=True, verbose_name='Observations')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.RequestCategory', verbose_name='Catégorie de la demande')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physical_document', models.FileField(upload_to='', verbose_name='Document')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.DocumentCategory', verbose_name='Document de reference')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Request', verbose_name='Demande correspondante')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='AdditionalInformation',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.TextField(verbose_name='Adresse')),
                ('postal_box', models.CharField(max_length=20, verbose_name='Boite postale')),
                ('phone', models.CharField(max_length=20, verbose_name='Mobile / Téléphone')),
                ('corps', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Corps', verbose_name='Corps')),
                ('ministry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.Ministry', verbose_name='Ministère')),
                ('paying_org', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.PayingOrg', verbose_name='Organisme payeur')),
            ],
            options={
                'ordering': ['created_at'],
                'abstract': False,
            },
        ),
    ]
