# Generated by Django 2.2.6 on 2019-10-19 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20191019_0120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='birth_place',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Lieu de naissance'),
        ),
        migrations.AlterField(
            model_name='user',
            name='cni',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Numéro Carte d'identité"),
        ),
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Prénom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_name',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='user',
            name='registration_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Matricule'),
        ),
        migrations.AlterField(
            model_name='user',
            name='sex',
            field=models.IntegerField(choices=[(0, 'Féminin'), (1, 'Masculin')], default=1, verbose_name='Sexe'),
        ),
    ]
