# Generated by Django 2.2.6 on 2019-10-23 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20191019_0150'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='amount',
        ),
        migrations.AddField(
            model_name='request',
            name='amount_awarded',
            field=models.FloatField(default=0, verbose_name='Montant accordé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='amount_requested',
            field=models.FloatField(default=0, verbose_name='Montant demandé'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='retirement_age',
            field=models.IntegerField(default=60, verbose_name='Age de la retraite'),
        ),
    ]
