# Generated by Django 2.2.6 on 2019-10-28 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20191028_1437'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.DocumentCategory', verbose_name='Document de reference'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='required_number',
            field=models.IntegerField(default=0, verbose_name='Nombre exigé'),
        ),
        migrations.AddField(
            model_name='documentcategory',
            name='required_number',
            field=models.IntegerField(default=1, verbose_name='Nombre exigé'),
        ),
        migrations.AlterField(
            model_name='document',
            name='physical_document',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Document'),
        ),
        migrations.AlterField(
            model_name='document',
            name='reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Nombre exigé'),
        ),
    ]
