# Generated by Django 2.2.6 on 2019-10-31 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_grade_corps'),
    ]

    operations = [
        migrations.AddField(
            model_name='grade',
            name='retired_to',
            field=models.IntegerField(default=60, verbose_name='Retraité à'),
            preserve_default=False,
        ),
    ]
