# Generated by Django 2.2.6 on 2019-10-31 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_grade_retired_to'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='additionalinformation',
            name='corps',
        ),
        migrations.AddField(
            model_name='additionalinformation',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Grade', verbose_name='Grade'),
            preserve_default=False,
        ),
    ]
