# Generated by Django 2.2.6 on 2019-11-03 17:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20191031_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.TextField(default='Dakar, Senegal', verbose_name='Adresse'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Grade', verbose_name='Grade'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='ministry',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.Ministry', verbose_name='Ministère'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='paying_org',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='users.PayingOrg', verbose_name='Organisme payeur'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=2210000000, max_length=20, verbose_name='Mobile / Téléphone'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='postal_box',
            field=models.CharField(default=0, max_length=20, verbose_name='Boite postale'),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='AdditionalInformation',
        ),
    ]
