# Generated by Django 2.2.6 on 2019-11-04 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_auto_20191103_1758'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='required_number',
        ),
        migrations.AddField(
            model_name='document',
            name='provided_number',
            field=models.IntegerField(default=0, verbose_name='Nombre fourni'),
        ),
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de dépôt de la demande'),
        ),
    ]
