# Generated by Django 2.2.6 on 2019-11-04 04:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20191104_0442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='amount_awarded',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant accordé'),
        ),
        migrations.AlterField(
            model_name='request',
            name='post_reference',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Référence courier'),
        ),
    ]
