# Generated by Django 2.2.6 on 2019-11-04 10:26

from django.db import migrations
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_request_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='accepted', max_length=100, no_check_for_status=True),
        ),
    ]
