# Generated by Django 2.2.6 on 2019-11-04 19:40

from django.db import migrations, models
import model_utils.fields


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_request_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='amount_to_repay',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant à rembourser'),
        ),
        migrations.AddField(
            model_name='request',
            name='monthly_payment_number',
            field=models.FloatField(blank=True, null=True, verbose_name='Nombre de mensualité'),
        ),
        migrations.AddField(
            model_name='request',
            name='quota',
            field=models.FloatField(blank=True, null=True, verbose_name='Quotité'),
        ),
        migrations.AddField(
            model_name='request',
            name='withholding',
            field=models.FloatField(blank=True, null=True, verbose_name='Précompte'),
        ),
        migrations.AlterField(
            model_name='request',
            name='amount_awarded',
            field=models.FloatField(blank=True, null=True, verbose_name='Montant prêt accordé'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=model_utils.fields.StatusField(choices=[(0, 'dummy')], default='pending', max_length=100, no_check_for_status=True),
        ),
    ]
