# Generated by Django 2.2.6 on 2019-11-05 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_auto_20191104_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='treatment_agent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agent de traitement'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='treatment_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date de traitement'),
        ),
    ]
