# Generated by Django 2.2.6 on 2019-11-05 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_auto_20191105_1123'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salary',
            name='user',
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Age de la retraite'),
        ),
    ]
