# Generated by Django 2.2.6 on 2019-11-05 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_auto_20191105_1126'),
    ]

    operations = [
        migrations.CreateModel(
            name='PrepaymentTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('loan_amount', models.FloatField(verbose_name='Montant du prêt')),
                ('duration', models.FloatField(verbose_name='Durée en années')),
                ('monthly_withdrawal', models.IntegerField(verbose_name='Prélévement mensuel')),
                ('recoverable_third_party', models.FloatField(verbose_name='Tiers saisissable')),
                ('minimal_salary', models.FloatField(verbose_name='Salaire minimum')),
            ],
            options={
                'verbose_name_plural': 'prepayment_table',
            },
        ),
        migrations.AlterField(
            model_name='request',
            name='monthly_payment_number',
            field=models.FloatField(blank=True, null=True, verbose_name='C. Nombre de mensualité'),
        ),
        migrations.AlterField(
            model_name='request',
            name='quota',
            field=models.FloatField(blank=True, null=True, verbose_name='D. Quotité = A / 3'),
        ),
        migrations.AlterField(
            model_name='request',
            name='withholding',
            field=models.FloatField(blank=True, null=True, verbose_name="E. Précompte = Montant prêt / <span id='id_n_months'>C</span>"),
        ),
    ]
