# Generated by Django 2.2.6 on 2019-11-05 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20191105_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='document_date',
            field=models.DateField(blank=True, null=True, verbose_name='Date pièce'),
        ),
    ]
