# Generated by Django 2.2.6 on 2019-12-04 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_document_document_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='retirement_age',
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.FloatField(default=0, verbose_name='Salaire'),
        ),
    ]
