# Generated by Django 2.2.6 on 2019-12-10 22:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0021_auto_20191204_0305'),
    ]

    operations = [
        migrations.AddField(
            model_name='request',
            name='convention',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Convention'),
        ),
    ]
