# Generated by Django 2.2.6 on 2019-12-10 23:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20191210_2302'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Profression',
            new_name='Profession',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='profression',
            new_name='profession',
        ),
    ]
