# Generated by Django 2.2.6 on 2019-12-12 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0024_auto_20191210_2304'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='treatment_date',
            new_name='proceed_date',
        ),
        migrations.RenameField(
            model_name='request',
            old_name='date',
            new_name='submit_date',
        ),
    ]
