# Generated by Django 2.2.6 on 2020-01-27 15:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_request_slip'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='address',
            field=models.TextField(blank=True, null=True, verbose_name='Adresse'),
        ),
        migrations.AlterField(
            model_name='user',
            name='grade',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Grade', verbose_name='Grade'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ministry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Ministry', verbose_name='Ministère'),
        ),
        migrations.AlterField(
            model_name='user',
            name='paying_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.PayingOrg', verbose_name='Organisme payeur'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Mobile / Téléphone'),
        ),
        migrations.AlterField(
            model_name='user',
            name='postal_box',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Boite postale'),
        ),
    ]
