# Generated by Django 2.2.6 on 2020-01-30 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_auto_20200127_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='slip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Slip', verbose_name='Bordereau'),
        ),
    ]
