# Generated by Django 2.2.6 on 2020-01-30 17:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0030_auto_20200130_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='treatment_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='treatment_agent', to=settings.AUTH_USER_MODEL, verbose_name='Agent de traitement'),
        ),
    ]
